version: '3'
services:
  backend:
    build: ./pom_planner_be  # Path to your backend Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=production
      - BE_RAILS_MASTER_KEY=${BE_RAILS_MASTER_KEY}

  frontend:
    build: ./pom_planner_fe  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000  # Adjust this depending on your API route
      - RAILS_ENV=production
      - FE_RAILS_MASTER_KEY=${FE_RAILS_MASTER_KEY}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
